#!/usr/bin/env python3

"""
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""

import os

def escape(line):
  line = line.replace("\\", "\\\\")  # Escape backslashes
  line = line.replace('"', '\\"')  # Escape double quotes
  line = line.replace("\n", "\\n")  # Escape newlines (which shouldn't be necessary)
  line = line.replace("\r", "\\r")  # Escape carriage returns
  line = line.replace("\t", "\\t")  # Escape tabs
  return line

def main():
  input_file = "src/core.fl"
  output_file = "h/core.fl.h"

  # Ensure output directory exists.
  os.makedirs(os.path.dirname(output_file), exist_ok=True)

  # Read input file.
  with open(input_file, "r", encoding="utf-8") as f:
    lines = f.readlines()

  # Escape each line (rstrip the newline at the end since we'll add \n explicitly).
  escaped_lines = [f'    "{escape(line.rstrip("\n\r"))}\\n"' for line in lines]

  # Write to output file
  with open(output_file, "w", encoding="utf-8") as f:
    f.write("/**\n")
    f.write(" * This Source Code Form is subject to the terms of the Mozilla Public\n")
    f.write(" * License, v. 2.0. If a copy of the MPL was not distributed with this\n")
    f.write(" * file, You can obtain one at https://mozilla.org/MPL/2.0/.\n")
    f.write(" */\n\n")
    f.write("// This file is generated by src/script/stringify-core.py. Do not edit directly.\n\n")
    f.write("#pragma once\n\n")
    f.write("#include <string_view>\n\n")
    f.write("namespace Core {\n");
    f.write("  constexpr std::string_view src {\n")
    f.write("\n".join(escaped_lines))
    f.write("\n  };\n")
    f.write("}\n")

if __name__ == "__main__":
  main()
