/**
* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by src/script/generate_ast.py. Do not edit directly.

#pragma once

#include <any>
#include <memory>

#include "lexer.h"

namespace Statements {
  class Block;
  class Expression;
  class Pass;
  class If;
  class While;
}

namespace Expressions {
  class Binary;
  class Unary;
  class Grouping;
  class Literal;
  class Print;
}

// Type-erased visitor base classes --------------------------------------------------
// These are type-erased so Stmt and Expr can accept any visitor; concrete visitors still type their result via StmtVisitor<R> or ExprVisitor<R>.
// This class only serves to bridge between a concrete visitor and an Expr.

class StmtVisitorAny {
public:
  virtual std::any visit_block_stmt_any(std::shared_ptr<Statements::Block> stmt) = 0;
  virtual std::any visit_expression_stmt_any(std::shared_ptr<Statements::Expression> stmt) = 0;
  virtual std::any visit_pass_stmt_any(std::shared_ptr<Statements::Pass> stmt) = 0;
  virtual std::any visit_if_stmt_any(std::shared_ptr<Statements::If> stmt) = 0;
  virtual std::any visit_while_stmt_any(std::shared_ptr<Statements::While> stmt) = 0;
  virtual ~StmtVisitorAny() = default;
};

class ExprVisitorAny {
public:
  virtual std::any visit_binary_expr_any(std::shared_ptr<Expressions::Binary> expr) = 0;
  virtual std::any visit_unary_expr_any(std::shared_ptr<Expressions::Unary> expr) = 0;
  virtual std::any visit_grouping_expr_any(std::shared_ptr<Expressions::Grouping> expr) = 0;
  virtual std::any visit_literal_expr_any(std::shared_ptr<Expressions::Literal> expr) = 0;
  virtual std::any visit_print_expr_any(std::shared_ptr<Expressions::Print> expr) = 0;
  virtual ~ExprVisitorAny() = default;
};

// Concrete visitor base classes --------------------------------------------------
// R is the return type for a concrete visitor. The _any member funcs adapt (dumb down) that typed visitor into the non-templated
// StmtVisitorAny/ExprVisitorAny interface so Stmt/Expr can always dispatch via std::any, while the concrete visitor still works with its real return type.

template <typename R>
class StmtVisitor : public StmtVisitorAny {
public:
  virtual R visit_block_stmt(std::shared_ptr<Statements::Block> stmt) = 0;
  virtual R visit_expression_stmt(std::shared_ptr<Statements::Expression> stmt) = 0;
  virtual R visit_pass_stmt(std::shared_ptr<Statements::Pass> stmt) = 0;
  virtual R visit_if_stmt(std::shared_ptr<Statements::If> stmt) = 0;
  virtual R visit_while_stmt(std::shared_ptr<Statements::While> stmt) = 0;

private:
  std::any visit_block_stmt_any(std::shared_ptr<Statements::Block> stmt) final {
    return visit_block_stmt(std::move(stmt));
  }

  std::any visit_expression_stmt_any(std::shared_ptr<Statements::Expression> stmt) final {
    return visit_expression_stmt(std::move(stmt));
  }

  std::any visit_pass_stmt_any(std::shared_ptr<Statements::Pass> stmt) final {
    return visit_pass_stmt(std::move(stmt));
  }

  std::any visit_if_stmt_any(std::shared_ptr<Statements::If> stmt) final {
    return visit_if_stmt(std::move(stmt));
  }

  std::any visit_while_stmt_any(std::shared_ptr<Statements::While> stmt) final {
    return visit_while_stmt(std::move(stmt));
  }
};

template <typename R>
class ExprVisitor : public ExprVisitorAny {
public:
  virtual R visit_binary_expr(std::shared_ptr<Expressions::Binary> expr) = 0;
  virtual R visit_unary_expr(std::shared_ptr<Expressions::Unary> expr) = 0;
  virtual R visit_grouping_expr(std::shared_ptr<Expressions::Grouping> expr) = 0;
  virtual R visit_literal_expr(std::shared_ptr<Expressions::Literal> expr) = 0;
  virtual R visit_print_expr(std::shared_ptr<Expressions::Print> expr) = 0;

private:
  std::any visit_binary_expr_any(std::shared_ptr<Expressions::Binary> expr) final {
    return visit_binary_expr(std::move(expr));
  }

  std::any visit_unary_expr_any(std::shared_ptr<Expressions::Unary> expr) final {
    return visit_unary_expr(std::move(expr));
  }

  std::any visit_grouping_expr_any(std::shared_ptr<Expressions::Grouping> expr) final {
    return visit_grouping_expr(std::move(expr));
  }

  std::any visit_literal_expr_any(std::shared_ptr<Expressions::Literal> expr) final {
    return visit_literal_expr(std::move(expr));
  }

  std::any visit_print_expr_any(std::shared_ptr<Expressions::Print> expr) final {
    return visit_print_expr(std::move(expr));
  }
};

// Base AST node classes --------------------------------------------------
class Stmt {
public:
  virtual std::any accept(StmtVisitorAny& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(StmtVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<StmtVisitorAny&>(visitor)));
  }

  virtual ~Stmt() = default;
};

class Expr {
public:
  virtual std::any accept(ExprVisitorAny& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(ExprVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<ExprVisitorAny&>(visitor)));
  }

  virtual ~Expr() = default;
};

// Aliases --------------------------------------------------
using StmtNode      = std::shared_ptr<Stmt>;
using ExprNode      = std::shared_ptr<Expr>;
using NamedFunction = std::string_view;

// Statements --------------------------------------------------
class Statements::Block : public Stmt, public std::enable_shared_from_this<Block> {
public:
  explicit Block(std::vector<StmtNode> statements) : statements {std::move(statements)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_block_stmt_any(shared_from_this());
  }

  const std::vector<StmtNode> statements {};
};

class Statements::Expression : public Stmt, public std::enable_shared_from_this<Expression> {
public:
  explicit Expression(ExprNode expression) : expression {std::move(expression)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_expression_stmt_any(shared_from_this());
  }

  const ExprNode expression {};
};

class Statements::Pass : public Stmt, public std::enable_shared_from_this<Pass> {
public:
  Pass() = default;

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_pass_stmt_any(shared_from_this());
  }

};

class Statements::If : public Stmt, public std::enable_shared_from_this<If> {
public:
  If(ExprNode condition, StmtNode then_body, StmtNode else_body) : condition {std::move(condition)}, then_body {std::move(then_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_if_stmt_any(shared_from_this());
  }

  const ExprNode condition {};
  const StmtNode then_body {};
  const StmtNode else_body {};
};

class Statements::While : public Stmt, public std::enable_shared_from_this<While> {
public:
  While(ExprNode condition, StmtNode loop_body, StmtNode else_body) : condition {std::move(condition)}, loop_body {std::move(loop_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_while_stmt_any(shared_from_this());
  }

  const ExprNode condition {};
  const StmtNode loop_body {};
  const StmtNode else_body {};
};

// Expressions --------------------------------------------------
class Expressions::Binary : public Expr, public std::enable_shared_from_this<Binary> {
public:
  Binary(const Token& op, NamedFunction fn_name, ExprNode left, ExprNode right) : op {op}, fn_name {fn_name}, left {std::move(left)}, right {std::move(right)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_binary_expr_any(shared_from_this());
  }

  const Token op {};
  const NamedFunction fn_name {};
  const ExprNode left {};
  const ExprNode right {};
};

class Expressions::Unary : public Expr, public std::enable_shared_from_this<Unary> {
public:
  Unary(const Token& op, NamedFunction fn_name, ExprNode expr) : op {op}, fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_unary_expr_any(shared_from_this());
  }

  const Token op {};
  const NamedFunction fn_name {};
  const ExprNode expr {};
};

class Expressions::Grouping : public Expr, public std::enable_shared_from_this<Grouping> {
public:
  explicit Grouping(ExprNode expr) : expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_grouping_expr_any(shared_from_this());
  }

  const ExprNode expr {};
};

class Expressions::Literal : public Expr, public std::enable_shared_from_this<Literal> {
public:
  explicit Literal(std::any value) : value {std::move(value)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_literal_expr_any(shared_from_this());
  }

  const std::any value {};
};

class Expressions::Print : public Expr, public std::enable_shared_from_this<Print> {
public:
  Print(const Token& op, NamedFunction fn_name, ExprNode expr) : op {op}, fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_print_expr_any(shared_from_this());
  }

  const Token op {};
  const NamedFunction fn_name {};
  const ExprNode expr {};
};
