/**
* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by src/script/generate_ast.py. Do not edit directly.

#pragma once

#include <any>
#include <memory>

#include "lexer.h"
#include "type.h"

namespace Statements {
  class Block;
  class Expression;
  class Variable;
  class If;
  class While;
  class Each;
  class For;
  class Break;
  class Continue;
  class Return;
  class Pass;
}

namespace Expressions {
  class Binary;
  class Comparison;
  class Unary;
  class Grouping;
  class Number;
  class Boolean;
  class Nil;
  class Char;
  class String;
  class Variable;
  class Print;
}

// Non-returning visitor base classes --------------------------------------------------
// std::any prefers a copy-constructible object, which void is not. So for a visitor that doesn't return anything, something like this is necessary.

class StmtVisitorVoid {
public:
  virtual void visit_block_stmt(std::shared_ptr<Statements::Block> stmt) = 0;
  virtual void visit_expression_stmt(std::shared_ptr<Statements::Expression> stmt) = 0;
  virtual void visit_variable_stmt(std::shared_ptr<Statements::Variable> stmt) = 0;
  virtual void visit_if_stmt(std::shared_ptr<Statements::If> stmt) = 0;
  virtual void visit_while_stmt(std::shared_ptr<Statements::While> stmt) = 0;
  virtual void visit_each_stmt(std::shared_ptr<Statements::Each> stmt) = 0;
  virtual void visit_for_stmt(std::shared_ptr<Statements::For> stmt) = 0;
  virtual void visit_break_stmt(std::shared_ptr<Statements::Break> stmt) = 0;
  virtual void visit_continue_stmt(std::shared_ptr<Statements::Continue> stmt) = 0;
  virtual void visit_return_stmt(std::shared_ptr<Statements::Return> stmt) = 0;
  virtual void visit_pass_stmt(std::shared_ptr<Statements::Pass> stmt) = 0;
  virtual ~StmtVisitorVoid() = default;
};

class ExprVisitorVoid {
public:
  virtual void visit_binary_expr(std::shared_ptr<Expressions::Binary> expr) = 0;
  virtual void visit_comparison_expr(std::shared_ptr<Expressions::Comparison> expr) = 0;
  virtual void visit_unary_expr(std::shared_ptr<Expressions::Unary> expr) = 0;
  virtual void visit_grouping_expr(std::shared_ptr<Expressions::Grouping> expr) = 0;
  virtual void visit_number_expr(std::shared_ptr<Expressions::Number> expr) = 0;
  virtual void visit_boolean_expr(std::shared_ptr<Expressions::Boolean> expr) = 0;
  virtual void visit_nil_expr(std::shared_ptr<Expressions::Nil> expr) = 0;
  virtual void visit_char_expr(std::shared_ptr<Expressions::Char> expr) = 0;
  virtual void visit_string_expr(std::shared_ptr<Expressions::String> expr) = 0;
  virtual void visit_variable_expr(std::shared_ptr<Expressions::Variable> expr) = 0;
  virtual void visit_print_expr(std::shared_ptr<Expressions::Print> expr) = 0;
  virtual ~ExprVisitorVoid() = default;
};

// Type-erased visitor base classes --------------------------------------------------
// These are type-erased so Stmt and Expr can accept any visitor; concrete visitors still type their result via StmtVisitor<R> or ExprVisitor<R>.
// This class only serves to bridge between a concrete visitor and an Expr.

class StmtVisitorAny {
public:
  virtual std::any visit_block_stmt_any(std::shared_ptr<Statements::Block> stmt) = 0;
  virtual std::any visit_expression_stmt_any(std::shared_ptr<Statements::Expression> stmt) = 0;
  virtual std::any visit_variable_stmt_any(std::shared_ptr<Statements::Variable> stmt) = 0;
  virtual std::any visit_if_stmt_any(std::shared_ptr<Statements::If> stmt) = 0;
  virtual std::any visit_while_stmt_any(std::shared_ptr<Statements::While> stmt) = 0;
  virtual std::any visit_each_stmt_any(std::shared_ptr<Statements::Each> stmt) = 0;
  virtual std::any visit_for_stmt_any(std::shared_ptr<Statements::For> stmt) = 0;
  virtual std::any visit_break_stmt_any(std::shared_ptr<Statements::Break> stmt) = 0;
  virtual std::any visit_continue_stmt_any(std::shared_ptr<Statements::Continue> stmt) = 0;
  virtual std::any visit_return_stmt_any(std::shared_ptr<Statements::Return> stmt) = 0;
  virtual std::any visit_pass_stmt_any(std::shared_ptr<Statements::Pass> stmt) = 0;
  virtual ~StmtVisitorAny() = default;
};

class ExprVisitorAny {
public:
  virtual std::any visit_binary_expr_any(std::shared_ptr<Expressions::Binary> expr) = 0;
  virtual std::any visit_comparison_expr_any(std::shared_ptr<Expressions::Comparison> expr) = 0;
  virtual std::any visit_unary_expr_any(std::shared_ptr<Expressions::Unary> expr) = 0;
  virtual std::any visit_grouping_expr_any(std::shared_ptr<Expressions::Grouping> expr) = 0;
  virtual std::any visit_number_expr_any(std::shared_ptr<Expressions::Number> expr) = 0;
  virtual std::any visit_boolean_expr_any(std::shared_ptr<Expressions::Boolean> expr) = 0;
  virtual std::any visit_nil_expr_any(std::shared_ptr<Expressions::Nil> expr) = 0;
  virtual std::any visit_char_expr_any(std::shared_ptr<Expressions::Char> expr) = 0;
  virtual std::any visit_string_expr_any(std::shared_ptr<Expressions::String> expr) = 0;
  virtual std::any visit_variable_expr_any(std::shared_ptr<Expressions::Variable> expr) = 0;
  virtual std::any visit_print_expr_any(std::shared_ptr<Expressions::Print> expr) = 0;
  virtual ~ExprVisitorAny() = default;
};

// Concrete visitor base classes --------------------------------------------------
// R is the return type for a concrete visitor. The _any member funcs adapt (dumb down) that typed visitor into the non-templated
// StmtVisitorAny/ExprVisitorAny interface so Stmt/Expr can always dispatch via std::any, while the concrete visitor still works with its real return type.

template <typename R>
class StmtVisitor : public StmtVisitorAny {
public:
  virtual R visit_block_stmt(std::shared_ptr<Statements::Block> stmt) = 0;
  virtual R visit_expression_stmt(std::shared_ptr<Statements::Expression> stmt) = 0;
  virtual R visit_variable_stmt(std::shared_ptr<Statements::Variable> stmt) = 0;
  virtual R visit_if_stmt(std::shared_ptr<Statements::If> stmt) = 0;
  virtual R visit_while_stmt(std::shared_ptr<Statements::While> stmt) = 0;
  virtual R visit_each_stmt(std::shared_ptr<Statements::Each> stmt) = 0;
  virtual R visit_for_stmt(std::shared_ptr<Statements::For> stmt) = 0;
  virtual R visit_break_stmt(std::shared_ptr<Statements::Break> stmt) = 0;
  virtual R visit_continue_stmt(std::shared_ptr<Statements::Continue> stmt) = 0;
  virtual R visit_return_stmt(std::shared_ptr<Statements::Return> stmt) = 0;
  virtual R visit_pass_stmt(std::shared_ptr<Statements::Pass> stmt) = 0;

private:
  std::any visit_block_stmt_any(std::shared_ptr<Statements::Block> stmt) final {
    return visit_block_stmt(std::move(stmt));
  }

  std::any visit_expression_stmt_any(std::shared_ptr<Statements::Expression> stmt) final {
    return visit_expression_stmt(std::move(stmt));
  }

  std::any visit_variable_stmt_any(std::shared_ptr<Statements::Variable> stmt) final {
    return visit_variable_stmt(std::move(stmt));
  }

  std::any visit_if_stmt_any(std::shared_ptr<Statements::If> stmt) final {
    return visit_if_stmt(std::move(stmt));
  }

  std::any visit_while_stmt_any(std::shared_ptr<Statements::While> stmt) final {
    return visit_while_stmt(std::move(stmt));
  }

  std::any visit_each_stmt_any(std::shared_ptr<Statements::Each> stmt) final {
    return visit_each_stmt(std::move(stmt));
  }

  std::any visit_for_stmt_any(std::shared_ptr<Statements::For> stmt) final {
    return visit_for_stmt(std::move(stmt));
  }

  std::any visit_break_stmt_any(std::shared_ptr<Statements::Break> stmt) final {
    return visit_break_stmt(std::move(stmt));
  }

  std::any visit_continue_stmt_any(std::shared_ptr<Statements::Continue> stmt) final {
    return visit_continue_stmt(std::move(stmt));
  }

  std::any visit_return_stmt_any(std::shared_ptr<Statements::Return> stmt) final {
    return visit_return_stmt(std::move(stmt));
  }

  std::any visit_pass_stmt_any(std::shared_ptr<Statements::Pass> stmt) final {
    return visit_pass_stmt(std::move(stmt));
  }
};

template <typename R>
class ExprVisitor : public ExprVisitorAny {
public:
  virtual R visit_binary_expr(std::shared_ptr<Expressions::Binary> expr) = 0;
  virtual R visit_comparison_expr(std::shared_ptr<Expressions::Comparison> expr) = 0;
  virtual R visit_unary_expr(std::shared_ptr<Expressions::Unary> expr) = 0;
  virtual R visit_grouping_expr(std::shared_ptr<Expressions::Grouping> expr) = 0;
  virtual R visit_number_expr(std::shared_ptr<Expressions::Number> expr) = 0;
  virtual R visit_boolean_expr(std::shared_ptr<Expressions::Boolean> expr) = 0;
  virtual R visit_nil_expr(std::shared_ptr<Expressions::Nil> expr) = 0;
  virtual R visit_char_expr(std::shared_ptr<Expressions::Char> expr) = 0;
  virtual R visit_string_expr(std::shared_ptr<Expressions::String> expr) = 0;
  virtual R visit_variable_expr(std::shared_ptr<Expressions::Variable> expr) = 0;
  virtual R visit_print_expr(std::shared_ptr<Expressions::Print> expr) = 0;

private:
  std::any visit_binary_expr_any(std::shared_ptr<Expressions::Binary> expr) final {
    return visit_binary_expr(std::move(expr));
  }

  std::any visit_comparison_expr_any(std::shared_ptr<Expressions::Comparison> expr) final {
    return visit_comparison_expr(std::move(expr));
  }

  std::any visit_unary_expr_any(std::shared_ptr<Expressions::Unary> expr) final {
    return visit_unary_expr(std::move(expr));
  }

  std::any visit_grouping_expr_any(std::shared_ptr<Expressions::Grouping> expr) final {
    return visit_grouping_expr(std::move(expr));
  }

  std::any visit_number_expr_any(std::shared_ptr<Expressions::Number> expr) final {
    return visit_number_expr(std::move(expr));
  }

  std::any visit_boolean_expr_any(std::shared_ptr<Expressions::Boolean> expr) final {
    return visit_boolean_expr(std::move(expr));
  }

  std::any visit_nil_expr_any(std::shared_ptr<Expressions::Nil> expr) final {
    return visit_nil_expr(std::move(expr));
  }

  std::any visit_char_expr_any(std::shared_ptr<Expressions::Char> expr) final {
    return visit_char_expr(std::move(expr));
  }

  std::any visit_string_expr_any(std::shared_ptr<Expressions::String> expr) final {
    return visit_string_expr(std::move(expr));
  }

  std::any visit_variable_expr_any(std::shared_ptr<Expressions::Variable> expr) final {
    return visit_variable_expr(std::move(expr));
  }

  std::any visit_print_expr_any(std::shared_ptr<Expressions::Print> expr) final {
    return visit_print_expr(std::move(expr));
  }
};

// Base AST node classes --------------------------------------------------
class Stmt {
public:
  virtual std::any accept(StmtVisitorAny& visitor) = 0;
  virtual void accept(StmtVisitorVoid& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(StmtVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<StmtVisitorAny&>(visitor)));
  }

  virtual ~Stmt() = default;
};

class Expr {
public:
  virtual std::any accept(ExprVisitorAny& visitor) = 0;
  virtual void accept(ExprVisitorVoid& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(ExprVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<ExprVisitorAny&>(visitor)));
  }

  virtual ~Expr() = default;
};

// Aliases --------------------------------------------------
using StmtNode      = std::shared_ptr<Stmt>;
using ExprNode      = std::shared_ptr<Expr>;
using NamedFunction = std::string_view;

// Statements --------------------------------------------------
class Statements::Block : public Stmt, public std::enable_shared_from_this<Block> {
public:
  explicit Block(std::vector<StmtNode> statements) : statements {std::move(statements)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_block_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_block_stmt(shared_from_this());
  }

  const std::vector<StmtNode> statements {};
};

class Statements::Expression : public Stmt, public std::enable_shared_from_this<Expression> {
public:
  explicit Expression(ExprNode expression) : expression {std::move(expression)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_expression_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_expression_stmt(shared_from_this());
  }

  const ExprNode expression {};
};

class Statements::Variable : public Stmt, public std::enable_shared_from_this<Variable> {
public:
  Variable(bool is_mutable, const Token* identifier, Type type, ExprNode initializer) : is_mutable {is_mutable}, identifier {identifier}, type {std::move(type)}, initializer {std::move(initializer)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_variable_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_variable_stmt(shared_from_this());
  }

  const bool is_mutable {};
  const Token* identifier {};
  const Type type {};
  const ExprNode initializer {};
};

class Statements::If : public Stmt, public std::enable_shared_from_this<If> {
public:
  If(ExprNode condition, StmtNode then_body, StmtNode else_body) : condition {std::move(condition)}, then_body {std::move(then_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_if_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_if_stmt(shared_from_this());
  }

  const ExprNode condition {};
  const StmtNode then_body {};
  const StmtNode else_body {};
};

class Statements::While : public Stmt, public std::enable_shared_from_this<While> {
public:
  While(const Token* label, ExprNode condition, StmtNode loop_body, StmtNode else_body) : label {label}, condition {std::move(condition)}, loop_body {std::move(loop_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_while_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_while_stmt(shared_from_this());
  }

  const Token* label {};
  const ExprNode condition {};
  const StmtNode loop_body {};
  const StmtNode else_body {};
};

class Statements::Each : public Stmt, public std::enable_shared_from_this<Each> {
public:
  Each(const Token* label, const Token* iter_var, const Token* index_var, ExprNode iterator, StmtNode loop_body, StmtNode else_body) : label {label}, iter_var {iter_var}, index_var {index_var}, iterator {std::move(iterator)}, loop_body {std::move(loop_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_each_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_each_stmt(shared_from_this());
  }

  const Token* label {};
  const Token* iter_var {};
  const Token* index_var {};
  const ExprNode iterator {};
  const StmtNode loop_body {};
  const StmtNode else_body {};
};

class Statements::For : public Stmt, public std::enable_shared_from_this<For> {
public:
  For(const Token* label, StmtNode begin, ExprNode condition, ExprNode end, StmtNode loop_body, StmtNode else_body) : label {label}, begin {std::move(begin)}, condition {std::move(condition)}, end {std::move(end)}, loop_body {std::move(loop_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_for_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_for_stmt(shared_from_this());
  }

  const Token* label {};
  const StmtNode begin {};
  const ExprNode condition {};
  const ExprNode end {};
  const StmtNode loop_body {};
  const StmtNode else_body {};
};

class Statements::Break : public Stmt, public std::enable_shared_from_this<Break> {
public:
  explicit Break(const Token* label) : label {label} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_break_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_break_stmt(shared_from_this());
  }

  const Token* label {};
};

class Statements::Continue : public Stmt, public std::enable_shared_from_this<Continue> {
public:
  explicit Continue(const Token* label) : label {label} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_continue_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_continue_stmt(shared_from_this());
  }

  const Token* label {};
};

class Statements::Return : public Stmt, public std::enable_shared_from_this<Return> {
public:
  explicit Return(ExprNode value) : value {std::move(value)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_return_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_return_stmt(shared_from_this());
  }

  const ExprNode value {};
};

class Statements::Pass : public Stmt, public std::enable_shared_from_this<Pass> {
public:
  Pass() = default;

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_pass_stmt_any(shared_from_this());
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_pass_stmt(shared_from_this());
  }

};

// Expressions --------------------------------------------------
class Expressions::Binary : public Expr, public std::enable_shared_from_this<Binary> {
public:
  Binary(NamedFunction fn_name, ExprNode left, ExprNode right) : fn_name {fn_name}, left {std::move(left)}, right {std::move(right)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_binary_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_binary_expr(shared_from_this());
  }

  const NamedFunction fn_name {};
  const ExprNode left {};
  const ExprNode right {};
};

class Expressions::Comparison : public Expr, public std::enable_shared_from_this<Comparison> {
public:
  Comparison(std::vector<NamedFunction> fn_names, std::vector<ExprNode> expressions) : fn_names {std::move(fn_names)}, expressions {std::move(expressions)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_comparison_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_comparison_expr(shared_from_this());
  }

  const std::vector<NamedFunction> fn_names {};
  const std::vector<ExprNode> expressions {};
};

class Expressions::Unary : public Expr, public std::enable_shared_from_this<Unary> {
public:
  Unary(NamedFunction fn_name, ExprNode expr) : fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_unary_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_unary_expr(shared_from_this());
  }

  const NamedFunction fn_name {};
  const ExprNode expr {};
};

class Expressions::Grouping : public Expr, public std::enable_shared_from_this<Grouping> {
public:
  explicit Grouping(ExprNode expr) : expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_grouping_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_grouping_expr(shared_from_this());
  }

  const ExprNode expr {};
};

class Expressions::Number : public Expr, public std::enable_shared_from_this<Number> {
public:
  explicit Number(double value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_number_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_number_expr(shared_from_this());
  }

  const double value {};
};

class Expressions::Boolean : public Expr, public std::enable_shared_from_this<Boolean> {
public:
  explicit Boolean(bool value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_boolean_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_boolean_expr(shared_from_this());
  }

  const bool value {};
};

class Expressions::Nil : public Expr, public std::enable_shared_from_this<Nil> {
public:
  Nil() = default;

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_nil_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_nil_expr(shared_from_this());
  }

};

class Expressions::Char : public Expr, public std::enable_shared_from_this<Char> {
public:
  explicit Char(char value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_char_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_char_expr(shared_from_this());
  }

  const char value {};
};

class Expressions::String : public Expr, public std::enable_shared_from_this<String> {
public:
  explicit String(std::string value) : value {std::move(value)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_string_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_string_expr(shared_from_this());
  }

  const std::string value {};
};

class Expressions::Variable : public Expr, public std::enable_shared_from_this<Variable> {
public:
  explicit Variable(const Token* identifier) : identifier {identifier} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_variable_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_variable_expr(shared_from_this());
  }

  const Token* identifier {};
};

class Expressions::Print : public Expr, public std::enable_shared_from_this<Print> {
public:
  Print(NamedFunction fn_name, ExprNode expr) : fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_print_expr_any(shared_from_this());
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_print_expr(shared_from_this());
  }

  const NamedFunction fn_name {};
  const ExprNode expr {};
};
