/**
* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by src/script/generate_ast.py. Do not edit directly.

#pragma once

#include <any>
#include <memory>

#include "lexer.h"
#include "param.h"
#include "type.h"

namespace Statements {
  class Block;
  class Expression;
  class Variable;
  class Function;
  class Initializer;
  class Method;
  class Class;
  class Namespace;
  class Import;
  class Typealias;
  class If;
  class While;
  class Each;
  class For;
  class Break;
  class Continue;
  class Return;
  class Pass;
}

namespace Expressions {
  class Binary;
  class Comparison;
  class If;
  class Call;
  class Subscript;
  class Member;
  class NamespaceMember;
  class Unary;
  class Interpolation;
  class Lambda;
  class Grouping;
  class List;
  class Map;
  class Number;
  class Boolean;
  class Nil;
  class Char;
  class String;
  class Variable;
  class This;
  class Super;
  class Print;
}

// Non-returning visitor base classes --------------------------------------------------
// std::any prefers a copy-constructible object, which void is not. So for a visitor that doesn't return anything, something like this is necessary.

class StmtVisitorVoid {
  public:
  virtual void visit_block_stmt(const Statements::Block& stmt) = 0;
  virtual void visit_expression_stmt(const Statements::Expression& stmt) = 0;
  virtual void visit_variable_stmt(const Statements::Variable& stmt) = 0;
  virtual void visit_function_stmt(const Statements::Function& stmt) = 0;
  virtual void visit_initializer_stmt(const Statements::Initializer& stmt) = 0;
  virtual void visit_method_stmt(const Statements::Method& stmt) = 0;
  virtual void visit_class_stmt(const Statements::Class& stmt) = 0;
  virtual void visit_namespace_stmt(const Statements::Namespace& stmt) = 0;
  virtual void visit_import_stmt(const Statements::Import& stmt) = 0;
  virtual void visit_typealias_stmt(const Statements::Typealias& stmt) = 0;
  virtual void visit_if_stmt(const Statements::If& stmt) = 0;
  virtual void visit_while_stmt(const Statements::While& stmt) = 0;
  virtual void visit_each_stmt(const Statements::Each& stmt) = 0;
  virtual void visit_for_stmt(const Statements::For& stmt) = 0;
  virtual void visit_break_stmt(const Statements::Break& stmt) = 0;
  virtual void visit_continue_stmt(const Statements::Continue& stmt) = 0;
  virtual void visit_return_stmt(const Statements::Return& stmt) = 0;
  virtual void visit_pass_stmt(const Statements::Pass& stmt) = 0;
  virtual ~StmtVisitorVoid() = default;
};

class ExprVisitorVoid {
  public:
  virtual void visit_binary_expr(const Expressions::Binary& expr) = 0;
  virtual void visit_comparison_expr(const Expressions::Comparison& expr) = 0;
  virtual void visit_if_expr(const Expressions::If& expr) = 0;
  virtual void visit_call_expr(const Expressions::Call& expr) = 0;
  virtual void visit_subscript_expr(const Expressions::Subscript& expr) = 0;
  virtual void visit_member_expr(const Expressions::Member& expr) = 0;
  virtual void visit_namespace_member_expr(const Expressions::NamespaceMember& expr) = 0;
  virtual void visit_unary_expr(const Expressions::Unary& expr) = 0;
  virtual void visit_interpolation_expr(const Expressions::Interpolation& expr) = 0;
  virtual void visit_lambda_expr(const Expressions::Lambda& expr) = 0;
  virtual void visit_grouping_expr(const Expressions::Grouping& expr) = 0;
  virtual void visit_list_expr(const Expressions::List& expr) = 0;
  virtual void visit_map_expr(const Expressions::Map& expr) = 0;
  virtual void visit_number_expr(const Expressions::Number& expr) = 0;
  virtual void visit_boolean_expr(const Expressions::Boolean& expr) = 0;
  virtual void visit_nil_expr(const Expressions::Nil& expr) = 0;
  virtual void visit_char_expr(const Expressions::Char& expr) = 0;
  virtual void visit_string_expr(const Expressions::String& expr) = 0;
  virtual void visit_variable_expr(const Expressions::Variable& expr) = 0;
  virtual void visit_this_expr(const Expressions::This& expr) = 0;
  virtual void visit_super_expr(const Expressions::Super& expr) = 0;
  virtual void visit_print_expr(const Expressions::Print& expr) = 0;
  virtual ~ExprVisitorVoid() = default;
};

// Type-erased visitor base classes --------------------------------------------------
// These are type-erased so Stmt and Expr can accept any visitor; concrete visitors still type their result via StmtVisitor<R> or ExprVisitor<R>.
// This class only serves to bridge between a concrete visitor and an Expr.

class StmtVisitorAny {
  public:
  virtual std::any visit_block_stmt_any(const Statements::Block& stmt) = 0;
  virtual std::any visit_expression_stmt_any(const Statements::Expression& stmt) = 0;
  virtual std::any visit_variable_stmt_any(const Statements::Variable& stmt) = 0;
  virtual std::any visit_function_stmt_any(const Statements::Function& stmt) = 0;
  virtual std::any visit_initializer_stmt_any(const Statements::Initializer& stmt) = 0;
  virtual std::any visit_method_stmt_any(const Statements::Method& stmt) = 0;
  virtual std::any visit_class_stmt_any(const Statements::Class& stmt) = 0;
  virtual std::any visit_namespace_stmt_any(const Statements::Namespace& stmt) = 0;
  virtual std::any visit_import_stmt_any(const Statements::Import& stmt) = 0;
  virtual std::any visit_typealias_stmt_any(const Statements::Typealias& stmt) = 0;
  virtual std::any visit_if_stmt_any(const Statements::If& stmt) = 0;
  virtual std::any visit_while_stmt_any(const Statements::While& stmt) = 0;
  virtual std::any visit_each_stmt_any(const Statements::Each& stmt) = 0;
  virtual std::any visit_for_stmt_any(const Statements::For& stmt) = 0;
  virtual std::any visit_break_stmt_any(const Statements::Break& stmt) = 0;
  virtual std::any visit_continue_stmt_any(const Statements::Continue& stmt) = 0;
  virtual std::any visit_return_stmt_any(const Statements::Return& stmt) = 0;
  virtual std::any visit_pass_stmt_any(const Statements::Pass& stmt) = 0;
  virtual ~StmtVisitorAny() = default;
};

class ExprVisitorAny {
  public:
  virtual std::any visit_binary_expr_any(const Expressions::Binary& expr) = 0;
  virtual std::any visit_comparison_expr_any(const Expressions::Comparison& expr) = 0;
  virtual std::any visit_if_expr_any(const Expressions::If& expr) = 0;
  virtual std::any visit_call_expr_any(const Expressions::Call& expr) = 0;
  virtual std::any visit_subscript_expr_any(const Expressions::Subscript& expr) = 0;
  virtual std::any visit_member_expr_any(const Expressions::Member& expr) = 0;
  virtual std::any visit_namespace_member_expr_any(const Expressions::NamespaceMember& expr) = 0;
  virtual std::any visit_unary_expr_any(const Expressions::Unary& expr) = 0;
  virtual std::any visit_interpolation_expr_any(const Expressions::Interpolation& expr) = 0;
  virtual std::any visit_lambda_expr_any(const Expressions::Lambda& expr) = 0;
  virtual std::any visit_grouping_expr_any(const Expressions::Grouping& expr) = 0;
  virtual std::any visit_list_expr_any(const Expressions::List& expr) = 0;
  virtual std::any visit_map_expr_any(const Expressions::Map& expr) = 0;
  virtual std::any visit_number_expr_any(const Expressions::Number& expr) = 0;
  virtual std::any visit_boolean_expr_any(const Expressions::Boolean& expr) = 0;
  virtual std::any visit_nil_expr_any(const Expressions::Nil& expr) = 0;
  virtual std::any visit_char_expr_any(const Expressions::Char& expr) = 0;
  virtual std::any visit_string_expr_any(const Expressions::String& expr) = 0;
  virtual std::any visit_variable_expr_any(const Expressions::Variable& expr) = 0;
  virtual std::any visit_this_expr_any(const Expressions::This& expr) = 0;
  virtual std::any visit_super_expr_any(const Expressions::Super& expr) = 0;
  virtual std::any visit_print_expr_any(const Expressions::Print& expr) = 0;
  virtual ~ExprVisitorAny() = default;
};

// Concrete visitor base classes --------------------------------------------------
// R is the return type for a concrete visitor. The _any member funcs adapt (dumb down) that typed visitor into the non-templated
// StmtVisitorAny/ExprVisitorAny interface so Stmt/Expr can always dispatch via std::any, while the concrete visitor still works with its real return type.

template <typename R>
class StmtVisitor : public StmtVisitorAny {
  public:
  virtual R visit_block_stmt(const Statements::Block& stmt) = 0;
  virtual R visit_expression_stmt(const Statements::Expression& stmt) = 0;
  virtual R visit_variable_stmt(const Statements::Variable& stmt) = 0;
  virtual R visit_function_stmt(const Statements::Function& stmt) = 0;
  virtual R visit_initializer_stmt(const Statements::Initializer& stmt) = 0;
  virtual R visit_method_stmt(const Statements::Method& stmt) = 0;
  virtual R visit_class_stmt(const Statements::Class& stmt) = 0;
  virtual R visit_namespace_stmt(const Statements::Namespace& stmt) = 0;
  virtual R visit_import_stmt(const Statements::Import& stmt) = 0;
  virtual R visit_typealias_stmt(const Statements::Typealias& stmt) = 0;
  virtual R visit_if_stmt(const Statements::If& stmt) = 0;
  virtual R visit_while_stmt(const Statements::While& stmt) = 0;
  virtual R visit_each_stmt(const Statements::Each& stmt) = 0;
  virtual R visit_for_stmt(const Statements::For& stmt) = 0;
  virtual R visit_break_stmt(const Statements::Break& stmt) = 0;
  virtual R visit_continue_stmt(const Statements::Continue& stmt) = 0;
  virtual R visit_return_stmt(const Statements::Return& stmt) = 0;
  virtual R visit_pass_stmt(const Statements::Pass& stmt) = 0;

  private:
  std::any visit_block_stmt_any(const Statements::Block& stmt) final {
    return visit_block_stmt(stmt);
  }

  std::any visit_expression_stmt_any(const Statements::Expression& stmt) final {
    return visit_expression_stmt(stmt);
  }

  std::any visit_variable_stmt_any(const Statements::Variable& stmt) final {
    return visit_variable_stmt(stmt);
  }

  std::any visit_function_stmt_any(const Statements::Function& stmt) final {
    return visit_function_stmt(stmt);
  }

  std::any visit_initializer_stmt_any(const Statements::Initializer& stmt) final {
    return visit_initializer_stmt(stmt);
  }

  std::any visit_method_stmt_any(const Statements::Method& stmt) final {
    return visit_method_stmt(stmt);
  }

  std::any visit_class_stmt_any(const Statements::Class& stmt) final {
    return visit_class_stmt(stmt);
  }

  std::any visit_namespace_stmt_any(const Statements::Namespace& stmt) final {
    return visit_namespace_stmt(stmt);
  }

  std::any visit_import_stmt_any(const Statements::Import& stmt) final {
    return visit_import_stmt(stmt);
  }

  std::any visit_typealias_stmt_any(const Statements::Typealias& stmt) final {
    return visit_typealias_stmt(stmt);
  }

  std::any visit_if_stmt_any(const Statements::If& stmt) final {
    return visit_if_stmt(stmt);
  }

  std::any visit_while_stmt_any(const Statements::While& stmt) final {
    return visit_while_stmt(stmt);
  }

  std::any visit_each_stmt_any(const Statements::Each& stmt) final {
    return visit_each_stmt(stmt);
  }

  std::any visit_for_stmt_any(const Statements::For& stmt) final {
    return visit_for_stmt(stmt);
  }

  std::any visit_break_stmt_any(const Statements::Break& stmt) final {
    return visit_break_stmt(stmt);
  }

  std::any visit_continue_stmt_any(const Statements::Continue& stmt) final {
    return visit_continue_stmt(stmt);
  }

  std::any visit_return_stmt_any(const Statements::Return& stmt) final {
    return visit_return_stmt(stmt);
  }

  std::any visit_pass_stmt_any(const Statements::Pass& stmt) final {
    return visit_pass_stmt(stmt);
  }
};

template <typename R>
class ExprVisitor : public ExprVisitorAny {
  public:
  virtual R visit_binary_expr(const Expressions::Binary& expr) = 0;
  virtual R visit_comparison_expr(const Expressions::Comparison& expr) = 0;
  virtual R visit_if_expr(const Expressions::If& expr) = 0;
  virtual R visit_call_expr(const Expressions::Call& expr) = 0;
  virtual R visit_subscript_expr(const Expressions::Subscript& expr) = 0;
  virtual R visit_member_expr(const Expressions::Member& expr) = 0;
  virtual R visit_namespace_member_expr(const Expressions::NamespaceMember& expr) = 0;
  virtual R visit_unary_expr(const Expressions::Unary& expr) = 0;
  virtual R visit_interpolation_expr(const Expressions::Interpolation& expr) = 0;
  virtual R visit_lambda_expr(const Expressions::Lambda& expr) = 0;
  virtual R visit_grouping_expr(const Expressions::Grouping& expr) = 0;
  virtual R visit_list_expr(const Expressions::List& expr) = 0;
  virtual R visit_map_expr(const Expressions::Map& expr) = 0;
  virtual R visit_number_expr(const Expressions::Number& expr) = 0;
  virtual R visit_boolean_expr(const Expressions::Boolean& expr) = 0;
  virtual R visit_nil_expr(const Expressions::Nil& expr) = 0;
  virtual R visit_char_expr(const Expressions::Char& expr) = 0;
  virtual R visit_string_expr(const Expressions::String& expr) = 0;
  virtual R visit_variable_expr(const Expressions::Variable& expr) = 0;
  virtual R visit_this_expr(const Expressions::This& expr) = 0;
  virtual R visit_super_expr(const Expressions::Super& expr) = 0;
  virtual R visit_print_expr(const Expressions::Print& expr) = 0;

  private:
  std::any visit_binary_expr_any(const Expressions::Binary& expr) final {
    return visit_binary_expr(expr);
  }

  std::any visit_comparison_expr_any(const Expressions::Comparison& expr) final {
    return visit_comparison_expr(expr);
  }

  std::any visit_if_expr_any(const Expressions::If& expr) final {
    return visit_if_expr(expr);
  }

  std::any visit_call_expr_any(const Expressions::Call& expr) final {
    return visit_call_expr(expr);
  }

  std::any visit_subscript_expr_any(const Expressions::Subscript& expr) final {
    return visit_subscript_expr(expr);
  }

  std::any visit_member_expr_any(const Expressions::Member& expr) final {
    return visit_member_expr(expr);
  }

  std::any visit_namespace_member_expr_any(const Expressions::NamespaceMember& expr) final {
    return visit_namespace_member_expr(expr);
  }

  std::any visit_unary_expr_any(const Expressions::Unary& expr) final {
    return visit_unary_expr(expr);
  }

  std::any visit_interpolation_expr_any(const Expressions::Interpolation& expr) final {
    return visit_interpolation_expr(expr);
  }

  std::any visit_lambda_expr_any(const Expressions::Lambda& expr) final {
    return visit_lambda_expr(expr);
  }

  std::any visit_grouping_expr_any(const Expressions::Grouping& expr) final {
    return visit_grouping_expr(expr);
  }

  std::any visit_list_expr_any(const Expressions::List& expr) final {
    return visit_list_expr(expr);
  }

  std::any visit_map_expr_any(const Expressions::Map& expr) final {
    return visit_map_expr(expr);
  }

  std::any visit_number_expr_any(const Expressions::Number& expr) final {
    return visit_number_expr(expr);
  }

  std::any visit_boolean_expr_any(const Expressions::Boolean& expr) final {
    return visit_boolean_expr(expr);
  }

  std::any visit_nil_expr_any(const Expressions::Nil& expr) final {
    return visit_nil_expr(expr);
  }

  std::any visit_char_expr_any(const Expressions::Char& expr) final {
    return visit_char_expr(expr);
  }

  std::any visit_string_expr_any(const Expressions::String& expr) final {
    return visit_string_expr(expr);
  }

  std::any visit_variable_expr_any(const Expressions::Variable& expr) final {
    return visit_variable_expr(expr);
  }

  std::any visit_this_expr_any(const Expressions::This& expr) final {
    return visit_this_expr(expr);
  }

  std::any visit_super_expr_any(const Expressions::Super& expr) final {
    return visit_super_expr(expr);
  }

  std::any visit_print_expr_any(const Expressions::Print& expr) final {
    return visit_print_expr(expr);
  }
};

// Base AST node classes --------------------------------------------------
class Stmt {
  public:
  virtual std::any accept(StmtVisitorAny& visitor) = 0;
  virtual void accept(StmtVisitorVoid& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(StmtVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<StmtVisitorAny&>(visitor)));
  }

  virtual ~Stmt() = default;
};

class Expr {
  public:
  virtual std::any accept(ExprVisitorAny& visitor) = 0;
  virtual void accept(ExprVisitorVoid& visitor) = 0;

  // To call a typed/concrete visitor without having to write the ugly std::any stuff.
  template <typename R>
  R accept(ExprVisitor<R>& visitor) {
    return std::any_cast<R>(accept(static_cast<ExprVisitorAny&>(visitor)));
  }

  virtual ~Expr() = default;
};

// Aliases --------------------------------------------------
using StmtNode      = std::shared_ptr<Stmt>;
using ExprNode      = std::shared_ptr<Expr>;
using NamedFunction = std::string_view;

// Statements --------------------------------------------------
class Statements::Block : public Stmt {
  public:
  explicit Block(std::vector<StmtNode> statements) : statements {std::move(statements)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_block_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_block_stmt(*this);
  }

  const std::vector<StmtNode> statements {};
};

class Statements::Expression : public Stmt {
  public:
  explicit Expression(ExprNode expression) : expression {std::move(expression)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_expression_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_expression_stmt(*this);
  }

  const ExprNode expression {};
};

class Statements::Variable : public Stmt {
  public:
  Variable(bool is_mutable, const Token* identifier, TypePtr type, ExprNode initializer) : is_mutable {is_mutable}, identifier {identifier}, type {std::move(type)}, initializer {std::move(initializer)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_variable_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_variable_stmt(*this);
  }

  const bool is_mutable {};
  const Token* identifier {};
  const TypePtr type {};
  const ExprNode initializer {};
};

class Statements::Function : public Stmt {
  public:
  Function(const Token* identifier, std::vector<Token*> type_params, std::vector<Param> params, TypePtr return_type, StmtNode body) : identifier {identifier}, type_params {std::move(type_params)}, params {std::move(params)}, return_type {std::move(return_type)}, body {std::move(body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_function_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_function_stmt(*this);
  }

  const Token* identifier {};
  const std::vector<Token*> type_params {};
  const std::vector<Param> params {};
  const TypePtr return_type {};
  const StmtNode body {};
};

class Statements::Initializer : public Stmt {
  public:
  Initializer(std::vector<Param> params, StmtNode body) : params {std::move(params)}, body {std::move(body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_initializer_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_initializer_stmt(*this);
  }

  const std::vector<Param> params {};
  const StmtNode body {};
};

class Statements::Method : public Stmt {
  public:
  Method(const Token* identifier, std::vector<Param> params, TypePtr return_type, StmtNode body) : identifier {identifier}, params {std::move(params)}, return_type {std::move(return_type)}, body {std::move(body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_method_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_method_stmt(*this);
  }

  const Token* identifier {};
  const std::vector<Param> params {};
  const TypePtr return_type {};
  const StmtNode body {};
};

class Statements::Class : public Stmt {
  public:
  Class(const Token* identifier, std::vector<Token*> type_params, const Token* superclass, std::vector<StmtNode> namespace_items, std::vector<StmtNode> initializers, std::vector<StmtNode> declarations) : identifier {identifier}, type_params {std::move(type_params)}, superclass {superclass}, namespace_items {std::move(namespace_items)}, initializers {std::move(initializers)}, declarations {std::move(declarations)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_class_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_class_stmt(*this);
  }

  const Token* identifier {};
  const std::vector<Token*> type_params {};
  const Token* superclass {};
  const std::vector<StmtNode> namespace_items {};
  const std::vector<StmtNode> initializers {};
  const std::vector<StmtNode> declarations {};
};

class Statements::Namespace : public Stmt {
  public:
  Namespace(const Token* identifier, std::vector<StmtNode> declarations) : identifier {identifier}, declarations {std::move(declarations)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_namespace_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_namespace_stmt(*this);
  }

  const Token* identifier {};
  const std::vector<StmtNode> declarations {};
};

class Statements::Import : public Stmt {
  public:
  Import(std::string path, std::vector<Token*> imports) : path {std::move(path)}, imports {std::move(imports)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_import_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_import_stmt(*this);
  }

  const std::string path {};
  const std::vector<Token*> imports {};
};

class Statements::Typealias : public Stmt {
  public:
  Typealias(const Token* identifier, TypePtr type) : identifier {identifier}, type {std::move(type)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_typealias_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_typealias_stmt(*this);
  }

  const Token* identifier {};
  const TypePtr type {};
};

class Statements::If : public Stmt {
  public:
  If(ExprNode condition, StmtNode then_body, StmtNode else_body) : condition {std::move(condition)}, then_body {std::move(then_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_if_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_if_stmt(*this);
  }

  const ExprNode condition {};
  const StmtNode then_body {};
  const StmtNode else_body {};
};

class Statements::While : public Stmt {
  public:
  While(const Token* label, ExprNode condition, StmtNode loop_body, StmtNode around_body, StmtNode else_body) : label {label}, condition {std::move(condition)}, loop_body {std::move(loop_body)}, around_body {std::move(around_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_while_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_while_stmt(*this);
  }

  const Token* label {};
  const ExprNode condition {};
  const StmtNode loop_body {};
  const StmtNode around_body {};
  const StmtNode else_body {};
};

class Statements::Each : public Stmt {
  public:
  Each(const Token* label, const Token* iter_var, const Token* index_var, ExprNode iterator, StmtNode loop_body, StmtNode around_body, StmtNode else_body) : label {label}, iter_var {iter_var}, index_var {index_var}, iterator {std::move(iterator)}, loop_body {std::move(loop_body)}, around_body {std::move(around_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_each_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_each_stmt(*this);
  }

  const Token* label {};
  const Token* iter_var {};
  const Token* index_var {};
  const ExprNode iterator {};
  const StmtNode loop_body {};
  const StmtNode around_body {};
  const StmtNode else_body {};
};

class Statements::For : public Stmt {
  public:
  For(const Token* label, StmtNode begin, ExprNode condition, ExprNode end, StmtNode loop_body, StmtNode around_body, StmtNode else_body) : label {label}, begin {std::move(begin)}, condition {std::move(condition)}, end {std::move(end)}, loop_body {std::move(loop_body)}, around_body {std::move(around_body)}, else_body {std::move(else_body)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_for_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_for_stmt(*this);
  }

  const Token* label {};
  const StmtNode begin {};
  const ExprNode condition {};
  const ExprNode end {};
  const StmtNode loop_body {};
  const StmtNode around_body {};
  const StmtNode else_body {};
};

class Statements::Break : public Stmt {
  public:
  explicit Break(const Token* label) : label {label} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_break_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_break_stmt(*this);
  }

  const Token* label {};
};

class Statements::Continue : public Stmt {
  public:
  explicit Continue(const Token* label) : label {label} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_continue_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_continue_stmt(*this);
  }

  const Token* label {};
};

class Statements::Return : public Stmt {
  public:
  explicit Return(ExprNode value) : value {std::move(value)} {}

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_return_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_return_stmt(*this);
  }

  const ExprNode value {};
};

class Statements::Pass : public Stmt {
  public:
  Pass() = default;

  std::any accept(StmtVisitorAny& visitor) override {
    return visitor.visit_pass_stmt_any(*this);
  }

  void accept(StmtVisitorVoid& visitor) override {
    visitor.visit_pass_stmt(*this);
  }

};

// Expressions --------------------------------------------------
class Expressions::Binary : public Expr {
  public:
  Binary(NamedFunction fn_name, ExprNode left, ExprNode right) : fn_name {fn_name}, left {std::move(left)}, right {std::move(right)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_binary_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_binary_expr(*this);
  }

  const NamedFunction fn_name {};
  const ExprNode left {};
  const ExprNode right {};
};

class Expressions::Comparison : public Expr {
  public:
  Comparison(std::vector<NamedFunction> fn_names, std::vector<ExprNode> expressions) : fn_names {std::move(fn_names)}, expressions {std::move(expressions)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_comparison_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_comparison_expr(*this);
  }

  const std::vector<NamedFunction> fn_names {};
  const std::vector<ExprNode> expressions {};
};

class Expressions::If : public Expr {
  public:
  If(ExprNode condition, ExprNode then, ExprNode else_expr) : condition {std::move(condition)}, then {std::move(then)}, else_expr {std::move(else_expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_if_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_if_expr(*this);
  }

  const ExprNode condition {};
  const ExprNode then {};
  const ExprNode else_expr {};
};

class Expressions::Call : public Expr {
  public:
  Call(ExprNode object, std::vector<ExprNode> arguments) : object {std::move(object)}, arguments {std::move(arguments)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_call_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_call_expr(*this);
  }

  const ExprNode object {};
  const std::vector<ExprNode> arguments {};
};

class Expressions::Subscript : public Expr {
  public:
  Subscript(ExprNode object, std::vector<ExprNode> arguments) : object {std::move(object)}, arguments {std::move(arguments)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_subscript_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_subscript_expr(*this);
  }

  const ExprNode object {};
  const std::vector<ExprNode> arguments {};
};

class Expressions::Member : public Expr {
  public:
  Member(ExprNode object, const Token* member, bool is_safe) : object {std::move(object)}, member {member}, is_safe {is_safe} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_member_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_member_expr(*this);
  }

  const ExprNode object {};
  const Token* member {};
  const bool is_safe {};
};

class Expressions::NamespaceMember : public Expr {
  public:
  NamespaceMember(const Token* namespace_id, const Token* member) : namespace_id {namespace_id}, member {member} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_namespace_member_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_namespace_member_expr(*this);
  }

  const Token* namespace_id {};
  const Token* member {};
};

class Expressions::Unary : public Expr {
  public:
  Unary(NamedFunction fn_name, ExprNode expr) : fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_unary_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_unary_expr(*this);
  }

  const NamedFunction fn_name {};
  const ExprNode expr {};
};

class Expressions::Interpolation : public Expr {
  public:
  Interpolation(std::string start, std::vector<ExprNode> expressions, std::vector<std::string> end_strings) : start {std::move(start)}, expressions {std::move(expressions)}, end_strings {std::move(end_strings)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_interpolation_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_interpolation_expr(*this);
  }

  const std::string start {};
  const std::vector<ExprNode> expressions {};
  const std::vector<std::string> end_strings {};
};

class Expressions::Lambda : public Expr {
  public:
  Lambda(std::vector<Param> params, StmtNode body) : params {std::move(params)}, body {std::move(body)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_lambda_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_lambda_expr(*this);
  }

  const std::vector<Param> params {};
  const StmtNode body {};
};

class Expressions::Grouping : public Expr {
  public:
  explicit Grouping(ExprNode expr) : expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_grouping_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_grouping_expr(*this);
  }

  const ExprNode expr {};
};

class Expressions::List : public Expr {
  public:
  explicit List(std::vector<ExprNode> items) : items {std::move(items)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_list_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_list_expr(*this);
  }

  const std::vector<ExprNode> items {};
};

class Expressions::Map : public Expr {
  public:
  Map(std::vector<std::string> keys, std::vector<ExprNode> values) : keys {std::move(keys)}, values {std::move(values)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_map_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_map_expr(*this);
  }

  const std::vector<std::string> keys {};
  const std::vector<ExprNode> values {};
};

class Expressions::Number : public Expr {
  public:
  explicit Number(double value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_number_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_number_expr(*this);
  }

  const double value {};
};

class Expressions::Boolean : public Expr {
  public:
  explicit Boolean(bool value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_boolean_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_boolean_expr(*this);
  }

  const bool value {};
};

class Expressions::Nil : public Expr {
  public:
  Nil() = default;

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_nil_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_nil_expr(*this);
  }

};

class Expressions::Char : public Expr {
  public:
  explicit Char(char value) : value {value} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_char_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_char_expr(*this);
  }

  const char value {};
};

class Expressions::String : public Expr {
  public:
  explicit String(std::string value) : value {std::move(value)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_string_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_string_expr(*this);
  }

  const std::string value {};
};

class Expressions::Variable : public Expr {
  public:
  explicit Variable(const Token* identifier) : identifier {identifier} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_variable_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_variable_expr(*this);
  }

  const Token* identifier {};
};

class Expressions::This : public Expr {
  public:
  explicit This(const Token* identifier) : identifier {identifier} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_this_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_this_expr(*this);
  }

  const Token* identifier {};
};

class Expressions::Super : public Expr {
  public:
  explicit Super(const Token* identifier) : identifier {identifier} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_super_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_super_expr(*this);
  }

  const Token* identifier {};
};

class Expressions::Print : public Expr {
  public:
  Print(NamedFunction fn_name, ExprNode expr) : fn_name {fn_name}, expr {std::move(expr)} {}

  std::any accept(ExprVisitorAny& visitor) override {
    return visitor.visit_print_expr_any(*this);
  }

  void accept(ExprVisitorVoid& visitor) override {
    visitor.visit_print_expr(*this);
  }

  const NamedFunction fn_name {};
  const ExprNode expr {};
};
