/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by src/script/stringify-core.py. Do not edit directly.

#pragma once

#include <string_view>

namespace Core {
  constexpr std::string_view src {
    "class Bool\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Number\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class String\n"
    "  fun test() = \"...\"\n"
  };
}
