/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#pragma once

#include "expr.h"
#include "flicker.h"

class Parser {
  antlr::flicker antlr_parser_;
  antlr::flicker::ProgramContext* tree_ {};

public:
  explicit Parser(antlr4::CommonTokenStream* token_stream);

  /**
   * Exports the parse tree generated by the parser in DOT format.
   * The DOT is saved to a file defined by DEBUG_DOT_FILENAME.
   */
  void output_dot();

  /**
* Parses the input token stream with an ANTLR4-generated parser and creates a parse tree which is stored as tree_ if there are no errors.
* @return True if parsing completes without syntax errors; otherwise false
*/
  bool parse_antlr();

  std::shared_ptr<Expr> parse_expression();

  /**
 * Parses the input token stream and generates an AST which is not stored yet. (TODO)
 * @return True if parsing completes without syntax errors; otherwise false
 */
  bool parse();
};
