/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#pragma once

#include "expr.h"
#include "flicker.h"

class ParserError {
public:
  Token token {};
  std::string message {};
  std::unique_ptr<ParserError> context {};

  ParserError(const Token& token, std::string&& message) : token {token}, message {std::move(message)} {}

  ParserError(const Token& token, std::string&& message, ParserError&& context) : token {token}, message {std::move(message)},
    context {std::make_unique<ParserError>(std::move(context))} {}

  void add_context(ParserError&& c) {
    this->context = std::make_unique<ParserError>(std::move(c));
  }

  [[nodiscard]] const char* what() const noexcept { return message.c_str(); }
};

enum class Precedence {
  NONE,
  ASSIGNMENT,     // = | -= | += | *= | /= | **= | |= | &= | ^= | %=
  NOT,            // not
  OR,             // or
  AND,            // and
  COMPARISON,     // == | != | > | >= | < | <=
  IN,             // in | not in
  IS,             // is | is not
  IF,             // ... if ... else ...
  BIT_OR,         // |
  BIT_XOR,        // ^
  BIT_AND,        // &
  BIT_SHIFT,      // << | >>
  TERM,           // + | -
  FACTOR,         // * | /
  PREFIX,         // ++ | -- | ! | ~ | -
  EXPONENT,       // **
  NIL_COALESCING, // ?:
  POSTFIX,        // ++ | -- | . | ?. | () | {} | []
  RANGE,          // .. | ..<
  ATOM
};

class Parser {
  antlr::flicker antlr_parser_;
  antlr::flicker::ProgramContext* tree_ {};

  Lexer& lexer_;
  std::shared_ptr<Expr> ast_ {};

  std::vector<Token> tokens_ {};
  Token* current_ {};
  Token* previous_ {};

  std::vector<ParserError> errors_ {};
  std::vector<ParserError> warnings_ {};

public:
  explicit Parser(antlr4::CommonTokenStream* token_stream, Lexer& lexer) : antlr_parser_ {token_stream}, lexer_ {lexer} {}

  /**
   * Exports the parse tree generated by the parser in DOT format.
   * The DOT is saved to a file defined by DEBUG_DOT_FILENAME.
   */
  void output_dot();

  /**
* Parses the input token stream with an ANTLR4-generated parser and creates a parse tree which is stored as tree_ if there are no errors.
* @return True if parsing completes without syntax errors; otherwise false
*/
  bool parse_antlr();

  explicit Parser(Lexer& lexer) : antlr_parser_ {nullptr}, lexer_ {lexer} {}

  void advance() {
    previous_ = current_;
    if (current_->type != TOKEN_EOF) ++current_;
  }

  /**
   * Returns a boolean of whether the next token is a certain type.
   * @param type The type to check for
   * @return A boolean, true if the token matches 'type'
   */
  [[nodiscard]] bool check(TokenType type) const {
    return current_->type == type;
  }

  /**
   * Advances if the next token matches a certain type, otherwise returns false.
   * @param type The type to check for
   * @return A boolean, true if the token matches 'type'
   */
  bool match(TokenType type) {
    if (!check(type)) return false;
    advance();
    return true;
  }

  /**
   * If the next token matches a certain type, advances, otherwise creates an error.
   * @param type The expected token type of the next token
   * @param message The error message if the expected TokenType is not found
   */
  void expect(TokenType type, std::string_view message) {
    if (current_->type != type) {
      advance();
      return;
    }
    errors_.emplace_back(*current_, std::string(message));
  }

  std::shared_ptr<Expr> binary(const std::shared_ptr<Expr>& left);
  std::shared_ptr<Expr> unary();
  std::shared_ptr<Expr> literal();
  std::shared_ptr<Expr> grouping();

  std::shared_ptr<Expr> parse_expression(Precedence precedence);

  /**
   * Fill the tokens_ vector with tokens from the lexer, up to ONE end-of-file token.
   * This allows the lexer to display all of its errors and warnings before the parser begins.
   * Also initializes current_ and previous_ (IMPORTANT! Must be called for this purpose).
   */
  void populate_token_vec();

  /**
   * Parses the input token stream and generates an AST which is stored in ast_ if there are no errors.
   * @return True if parsing completes without syntax errors; otherwise false
   */
  bool parse();

  using PrefixFn = std::shared_ptr<Expr>(Parser::*)();
  using InfixFn  = std::shared_ptr<Expr>(Parser::*)(const std::shared_ptr<Expr>&);

  struct ParseRule {
    PrefixFn prefix;
    InfixFn infix;
    Precedence prec;
  };

  #define UNUSED              ParseRule {nullptr, nullptr, Precedence::NONE}
  #define INFIX(fn, prec)     ParseRule {nullptr, &Parser::fn, Precedence::prec}
  #define PREFIX(fn, prec)    ParseRule {&Parser::fn, nullptr, Precedence::prec}
  #define BOTH(pre, in, prec) ParseRule {&Parser::pre, &Parser::in, Precedence::prec}

  // @formatter:off
  std::array<ParseRule, 91> rules {{
    /* TOKEN_LEFT_PAREN    *//* BOTH(grouping, call, POSTFIX),*/ PREFIX(grouping, NONE),
    /* TOKEN_RIGHT_PAREN   */ UNUSED,
    /* TOKEN_LEFT_BRACKET  *//* BOTH(collection, subscript, POSTFIX),*/ UNUSED,
    /* TOKEN_RIGHT_BRACKET */ UNUSED,
    /* TOKEN_LEFT_BRACE    *//* INFIX(lambda_call, POSTFIX),*/ UNUSED,
    /* TOKEN_RIGHT_BRACE   */ UNUSED,
    /* TOKEN_SEMICOLON     */ UNUSED,
    /* TOKEN_COMMA         */ UNUSED,
    /* TOKEN_TILDE         */ PREFIX(unary, PREFIX),
    /* TOKEN_STAR          */ INFIX(binary, FACTOR),
    /* TOKEN_STAR_STAR     */ INFIX(binary, EXPONENT),
    /* TOKEN_STAR_EQ       */ UNUSED,
    /* TOKEN_STAR_STAR_EQ  */ UNUSED,
    /* TOKEN_MINUS         */ BOTH(unary, binary, TERM),
    /* TOKEN_MINUS_MINUS   *//* BOTH(unary, postfix, POSTFIX),*/ UNUSED,
    /* TOKEN_RIGHT_ARROW   */ UNUSED,
    /* TOKEN_MINUS_EQ      */ UNUSED,
    /* TOKEN_PLUS          */ INFIX(binary, TERM),
    /* TOKEN_PLUS_PLUS     *//* BOTH(unary, postfix, POSTFIX),*/ UNUSED,
    /* TOKEN_PLUS_EQ       */ UNUSED,
    /* TOKEN_DOT           *//* INFIX(dot, POSTFIX),*/ UNUSED,
    /* TOKEN_DOT_DOT       */ INFIX(binary, RANGE),
    /* TOKEN_DOT_DOT_LT    */ INFIX(binary, RANGE),
    /* TOKEN_QUEST         */ UNUSED,
    /* TOKEN_QUEST_COLON   */ INFIX(binary, NIL_COALESCING),
    /* TOKEN_QUEST_DOT     *//* INFIX(dot, POSTFIX),*/ UNUSED,
    /* TOKEN_GT            */ INFIX(binary, COMPARISON),
    /* TOKEN_GT_GT         */ INFIX(binary, BIT_SHIFT),
    /* TOKEN_GT_EQ         */ INFIX(binary, COMPARISON),
    /* TOKEN_LT            */ INFIX(binary, COMPARISON),
    /* TOKEN_LT_LT         */ INFIX(binary, BIT_SHIFT),
    /* TOKEN_LT_EQ         */ INFIX(binary, COMPARISON),
    /* TOKEN_COLON         */ UNUSED,
    /* TOKEN_COLON_COLON   *//* INFIX(scope_access, ATOM),*/ UNUSED,
    /* TOKEN_SLASH         */ INFIX(binary, FACTOR),
    /* TOKEN_SLASH_EQ      */ UNUSED,
    /* TOKEN_PERCENT       */ INFIX(binary, FACTOR),
    /* TOKEN_PERCENT_EQ    */ UNUSED,
    /* TOKEN_PIPE          */ INFIX(binary, BIT_OR),
    /* TOKEN_PIPE_EQ       */ UNUSED,
    /* TOKEN_CARET         */ INFIX(binary, BIT_XOR),
    /* TOKEN_CARET_EQ      */ UNUSED,
    /* TOKEN_AMPERSAND     */ INFIX(binary, BIT_AND),
    /* TOKEN_AMPERSAND_EQ  */ UNUSED,
    /* TOKEN_BANG          */ PREFIX(unary, PREFIX),
    /* TOKEN_BANG_EQ       */ INFIX(binary, COMPARISON),
    /* TOKEN_EQ            */ INFIX(binary, COMPARISON),
    /* TOKEN_EQ_EQ         */ INFIX(binary, COMPARISON),
    /* TOKEN_IDENTIFIER    *//* PREFIX(identifier, NONE),*/ UNUSED,
    /* TOKEN_STRING        */ PREFIX(literal, NONE),
    /* TOKEN_INTERPOLATION *//* PREFIX(string_interpolation, NONE),*/ UNUSED,
    /* TOKEN_CHAR          */ PREFIX(literal, NONE),
    /* TOKEN_NUMBER        */ PREFIX(literal, NONE),
    /* TOKEN_AND           */ INFIX(binary, AND),
    /* TOKEN_BREAK         */ UNUSED,
    /* TOKEN_CLASS         */ UNUSED,
    /* TOKEN_CONTINUE      */ UNUSED,
    /* TOKEN_DO            */ UNUSED,
    /* TOKEN_EACH          */ UNUSED,
    /* TOKEN_ELIF          */ UNUSED,
    /* TOKEN_ELSE          */ UNUSED,
    /* TOKEN_FALSE         */ PREFIX(literal, NONE),
    /* TOKEN_FOR           */ UNUSED,
    /* TOKEN_FUN           */ UNUSED,
    /* TOKEN_IF            *//* INFIX(if_expr, IF),*/ UNUSED,
    /* TOKEN_IN            */ INFIX(binary, IN),
    /* TOKEN_IS            */ INFIX(binary, IS),
    /* TOKEN_NAMESPACE     */ UNUSED,
    /* TOKEN_NIL           */ PREFIX(literal, NONE),
    /* TOKEN_NOT           *//* BOTH(unary, not_in, IN),*/ UNUSED,
    /* TOKEN_OF            *//* PREFIX(of, ATOM),*/ UNUSED,
    /* TOKEN_OR            */ INFIX(binary, OR),
    /* TOKEN_OVERRIDE      */ UNUSED,
    /* TOKEN_PASS          */ UNUSED,
    /* TOKEN_PRINT         */ UNUSED,
    /* TOKEN_PRINT_ERROR   */ UNUSED,
    /* TOKEN_PRIVATE       */ UNUSED,
    /* TOKEN_RETURN        */ UNUSED,
    /* TOKEN_STATIC        */ UNUSED,
    /* TOKEN_SUPER         *//* PREFIX(super_id, NONE),*/ UNUSED,
    /* TOKEN_THIS          *//* PREFIX(this_id, NONE),*/ UNUSED,
    /* TOKEN_TRUE          */ PREFIX(literal, NONE),
    /* TOKEN_USING         */ UNUSED,
    /* TOKEN_VAL           */ UNUSED,
    /* TOKEN_VAR           */ UNUSED,
    /* TOKEN_WHEN          */ UNUSED,
    /* TOKEN_WHILE         */ UNUSED,
    /* TOKEN_INDENT        */ UNUSED,
    /* TOKEN_DEDENT        */ UNUSED,
    /* TOKEN_LINE          */ UNUSED,
    /* TOKEN_EOF           */ UNUSED,
  }};
  // @formatter:on
};
