/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// This file is generated by src/script/stringify-core.py. Do not edit directly.

export module core;

import std;

export namespace Core {
  constexpr std::string_view SRC {
    "class Unit\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Bool\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Char\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Sequence of A\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class List of A\n"
    "  is Sequence of A\n"
    "\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Map of A\n"
    "  is Sequence of A\n"
    "\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class String\n"
    "  is Sequence of Char\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Nothing\n"
    "  fun test() = \"...\"\n"
    "\n"
    "class Number\n"
    "  fun test() = \"...\"\n"
  };
}
